/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dewey
 */
public class ConverterUI extends javax.swing.JFrame {
    
    public ConverterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btn_InchesToCm = new javax.swing.JButton();
        txt_Inches = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_CmToInches = new javax.swing.JButton();
        txt_Cm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_FeetToMeters = new javax.swing.JButton();
        btn_MetersToFeet = new javax.swing.JButton();
        txt_Feet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Meters = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_InchesToCm.setText("Inches to Centimetres");
        btn_InchesToCm.setToolTipText("Put your measurement in the inches text box and click here to convert it to centimetres!");

        txt_Inches.setToolTipText("Put your inches in here!");

        jLabel1.setText("Inches");

        btn_CmToInches.setText("Centimetres to Inches");
        btn_CmToInches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CmToInchesActionPerformed(evt);
            }
        });

        txt_Cm.setToolTipText("Put your inches in here!");
        txt_Cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CmActionPerformed(evt);
            }
        });

        jLabel2.setText("Centimetres");

        btn_FeetToMeters.setText("Feet to Meters");
        btn_FeetToMeters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FeetToMetersActionPerformed(evt);
            }
        });

        btn_MetersToFeet.setText("Meters to Feet");
        btn_MetersToFeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MetersToFeetActionPerformed(evt);
            }
        });

        txt_Feet.setToolTipText("Put your inches in here!");

        jLabel3.setText("Feet");

        txt_Meters.setToolTipText("Put your inches in here!");
        txt_Meters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MetersActionPerformed(evt);
            }
        });

        jLabel4.setText("Meters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_CmToInches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MetersToFeet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_Cm, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(txt_Inches, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_Meters, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Feet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_FeetToMeters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_InchesToCm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InchesToCm)
                    .addComponent(txt_Inches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CmToInches)
                    .addComponent(txt_Cm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_FeetToMeters)
                    .addComponent(btn_MetersToFeet)
                    .addComponent(txt_Meters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Feet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CmToInchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CmToInchesActionPerformed
        //declaring the variable for centimetres
        //and collecting its data from the text box
        double cm;
        cm = Double.parseDouble(txt_Cm.getText());
        
        //declaring inches and running the conversion formula
        double inches;
        inches = Math.round( (cm / 2.54) * 100.0 ) / 100.0;
        
        //putting the result into the inches textbox
        txt_Inches.setText(String.valueOf(inches));
    }//GEN-LAST:event_btn_CmToInchesActionPerformed

    private void txt_CmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CmActionPerformed

    private void btn_FeetToMetersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FeetToMetersActionPerformed
        //declaring feet and getting the data from the text box
        double feet;
        feet = Double.parseDouble(txt_Feet.getText());
        
        //declaring meters and running the conversion formula
        double meters;
        meters = Math.round( (feet * 0.3048) * 100.0) / 100.0;
        
        //putting the result into the meters textbox
        txt_Meters.setText(String.valueOf(meters));
    }//GEN-LAST:event_btn_FeetToMetersActionPerformed

    private void btn_MetersToFeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MetersToFeetActionPerformed
        //declaring meters and getting the data from the text box
        double meters;
        meters = Double.parseDouble(txt_Meters.getText());
        
        //declaring meters and running the conversion formula
        double feet;
        feet = Math.round( (meters / 0.3048) * 100.0) / 100.0;
        
        //putting the result into the feet textbox
        txt_Feet.setText(String.valueOf(feet));
    }//GEN-LAST:event_btn_MetersToFeetActionPerformed

    private void txt_MetersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MetersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MetersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CmToInches;
    private javax.swing.JButton btn_FeetToMeters;
    private javax.swing.JButton btn_InchesToCm;
    private javax.swing.JButton btn_MetersToFeet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_Cm;
    private javax.swing.JTextField txt_Feet;
    private javax.swing.JTextField txt_Inches;
    private javax.swing.JTextField txt_Meters;
    // End of variables declaration//GEN-END:variables
}
